from pathlib import Path
import argparse
import sys


ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
PARTS = [
    ROOT / "docs" / "README.ja.md",
    ROOT / "docs" / "README.en.md",
]


def build() -> str:
    body = [
        "# fvCapture",
        "",
        "[日本語](#日本語) | [English](#english)",
        "",
        "<!-- This file is generated by scripts/build_readme.py. Edit docs/README.*.md instead. -->",
        "",
    ]
    for index, part in enumerate(PARTS):
        if index:
            body.extend(["", "---", ""])
        body.append(part.read_text(encoding="utf-8").strip())
        body.append("")
    return "\n".join(body).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    content = build()
    if args.check:
        current = README.read_text(encoding="utf-8") if README.exists() else ""
        if current != content:
            print("README.md is stale. Run: python scripts/build_readme.py", file=sys.stderr)
            return 1
        return 0

    README.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
